from enum import Enum

class Location(Enum):
    HOME = "HOME"
    AWAY = "AWAY"

class Outcome(Enum):
    WIN = "WIN"
    LOSS = "LOSS"

class Teams(Enum):
    ATLANTA_HAWKS = "ATLANTA HAWKS"
    BOSTON_CELTICS = "BOSTON CELTICS"
    BROOKLYN_NETS = "BROOKLYN NETS"
    CHARLOTTE_HORNETS = "CHARLOTTE HORNETS"
    CHICAGO_BULLS = "CHICAGO BULLS"
    CLEVELAND_CAVALIERS = "CLEVELAND CAVALIERS"
    DALLAS_MAVERICKS = "DALLAS MAVERICKS"
    DENVER_NUGGETS = "DENVER NUGGETS"
    DETROIT_PISTONS = "DETROIT PISTONS"
    GOLDEN_STATE_WARRIORS = "GOLDEN STATE WARRIRORS"
    HOUSTON_ROCKETS = "HOUSTON ROCKETS"
    INDIANA_PACERS = "INDIANA PACERS"
    LOS_ANGELES_CLIPPERS = "LOS ANGELES CLIPPERS"
    LOS_ANGELES_LAKERS = "LOS ANGELES LAKERS"
    MEMPHIS_GRIZZLIES = "MEMPHIS GRIZZLIES"
    MIAMI_HEAT = "MIAMI HEAT"
    MILWAUKEE_BUCKS = "MILKWAUKEE BUCKS"
    MINNESOTA_TIMBERWOLVES = "MINNESOTA TIMBERWOLVES"
    NEW_ORLEANS_PELICANS = "NEW ORLEANS PELICANS"
    NEW_YORK_KNICKS = "NEW YORK KNICKS"
    OKLAHOMA_CITY_THUNDER = "OKLAHOMA CITY THUNDER"
    ORLANDO_MAGIC = "ORLANDO MAGIC"
    PHILADELPHIA_76ERS = "PHILADELPHIA 76ERS"
    PHOENIX_SUNS = "PHOENIX SUNS"
    PORTLAND_TRAIL_BLAZERS = "PORTLAND TRAIL BLAZERS"
    SACRAMENTO_KINGS = "SACRAMENTO KINGS"
    SAN_ANTONIO_SPURS = "SAN ANTONIO SPURS"
    TORONTO_RAPTORS = "TORONTO RAPTORS"
    UTAH_JAZZ = "UTAH JAZZ"
    WASHINGTON_WIZARDS = "WASHINGTON WIZARDS"

class OutputType(Enum):
    JSON = "JSON"

class OutputWriteOptions(Enum):
    WRITE = "w"
    CREATE_AND_WRITE = "w+"
    APPEND = "a"
    APPEND_AND_WRITE = "a+"

class Position(Enum):
    POINT_GUARD = "POINT GUARD"
    SHOOTING_GUARD = "SHOOTING GUARD"
    SMALL_FORWARD = "SMALL FORWARD"
    POWER_FORWARD = "POWER FORWARD"
    CENTER = "CENTER"
    FORWARD_GUARD = "FORWARD-GUARD"
    FORWARD = "FORWARD"
    GUARD_FORWARD = "GUARD-FORWARD"
    FORWARD_CENTER = "FORWARD-CENTER"
    GUARD = "GUARD"

TEAM_ABBREVIATIONS_TO_TEAM = {
    'ATL': Teams.ATLANTA_HAWKS,
    'BOS': Teams.BOSTON_CELTICS,
    'BRK': Teams.BROOKLYN_NETS,
    'CHI': Teams.CHICAGO_BULLS,
    'CHO': Teams.CHARLOTTE_HORNETS,
    'CLE': Teams.CLEVELAND_CAVALIERS,
    'DAL': Teams.DALLAS_MAVERICKS,
    'DEN': Teams.DENVER_NUGGETS,
    'DET': Teams.DETROIT_PISTONS,
    'GSW': Teams.GOLDEN_STATE_WARRIORS,
    'HOU': Teams.HOUSTON_ROCKETS,
    'IND': Teams.INDIANA_PACERS,
    'LAC': Teams.LOS_ANGELES_CLIPPERS,
    'LAL': Teams.LOS_ANGELES_LAKERS,
    'MEM': Teams.MEMPHIS_GRIZZLIES,
    'MIA': Teams.MIAMI_HEAT,
    'MIL': Teams.MILWAUKEE_BUCKS,
    'MIN': Teams.MINNESOTA_TIMBERWOLVES,
    'NOP': Teams.NEW_ORLEANS_PELICANS,
    'NYK': Teams.NEW_YORK_KNICKS,
    'OKC': Teams.OKLAHOMA_CITY_THUNDER,
    'ORL': Teams.ORLANDO_MAGIC,
    'PHI': Teams.PHILADELPHIA_76ERS,
    'PHO': Teams.PHOENIX_SUNS,
    'POR': Teams.PORTLAND_TRAIL_BLAZERS,
    'SAC': Teams.SACRAMENTO_KINGS,
    'SAS': Teams.SAN_ANTONIO_SPURS,
    'TOR': Teams.TORONTO_RAPTORS,
    'UTA': Teams.UTAH_JAZZ,
    'WAS': Teams.WASHINGTON_WIZARDS
}

POSITION_ABBREVIATIONS_TO_POSITION = {
    "PG": Position.POINT_GUARD,
    "SG": Position.SHOOTING_GUARD,
    "SF": Position.SMALL_FORWARD,
    "PF": Position.POWER_FORWARD,
    "C": Position.CENTER,
    "F-G": Position.FORWARD_GUARD,
    "F": Position.FORWARD,
    "G-F": Position.GUARD_FORWARD,
    "F-C": Position.FORWARD_CENTER,
    "G": Position.GUARD,
}